function [] = save_data()
%% save_data saves data as an xlsx file

global info
global vals

if contains(info.assaytype, 'Bact_4.9') || contains(info.assaytype, 'C02_3.75') ...
        || contains(info.assaytype, 'Pher_5') || contains(info.assaytype, 'Odor_5')
    
    headers={'Distance_Ratio', 'Mean_Speed_cm_per_s', ...
        'Pathlength_cm', 'Final_Location_Relative_to_Control_cm', ...
        'Final_Location_Relative_to_Experimental_cm', ...
        'Time_in_Control_Zone_sec', 'Time_in_Experimental_Zone_sec'};
    T=table(vals.distanceratio', vals.meanspeed', ...
        vals.pathlength', vals.EndLoc.Cport', ...
        vals.EndLoc.Eport', vals.zonetime.C',...
        vals.zonetime.E','VariableNames',...
        headers);
    writetable(T,fullfile(info.pathstr,info.name,strcat(info.name,'_results.xlsx')));
    
    TT=table(vals.nfinal.C, vals.nfinal.E,'VariableNames', ...
        {'number_of_worms_ending_in_Control_Zone', 'number_of_worms_ending_in_Experimenal_Zone'});
    writetable(TT,fullfile(info.pathstr,info.name, strcat(info.name,'_Ctrls_vs_Exp_count.xlsx')));
    
    TTT=table(vals.instantspeed,'VariableNames',{'InstantSpeed'});
    writetable(TTT,fullfile(info.pathstr,info.name,strcat(info.name,'_instantspeed.xlsx')));
    
elseif contains(info.assaytype, 'Custom_linear') || contains(info.assaytype, 'Thermo_22')
    headers={'Final_location_in_gradient', 'Change_in_gradient_location',...
        'Distance_Ratio', 'Mean_Speed_cm_per_s', ...
        'Pathlength_cm'};
    T=table(vals.finalgradientval', vals.gradientdiff',...
        vals.distanceratio', vals.meanspeed', ...
        vals.pathlength','VariableNames',...
        headers);
    
    writetable(T,fullfile(info.pathstr,info.name,strcat(info.name,'_results.xlsx')));
    
elseif contains(info.assaytype, 'Basic_info')
    headers={'Distance_Ratio', 'Mean_Speed_cm_per_s', ...
        'Pathlength_cm'};
    T=table(vals.distanceratio', vals.meanspeed', ...
        vals.pathlength','VariableNames',...
        headers);
    
    writetable(T,fullfile(info.pathstr,info.name,strcat(info.name,'_results.xlsx')));

    TTT=table(vals.instantspeed,'VariableNames',{'InstantSpeed'});
    writetable(TTT,fullfile(info.pathstr,info.name,strcat(info.name,'_instantspeed.xlsx')));
    
end
end